feat: setup dns + ssl certificate and auto cd pipeline
* remove combo row

* update cd pipeline

* support clone with specific commit

* update owner

* update owner

* fix checkout command

* move traefik to app docker compose

* stop app first before start app

* dont need .env file when compose down

* export the app port

* fetch secrets before start app

* update .env file

* update stop-app

* update env path

* add localhost to address

* update host config with domain name

* update host

* update port

* update host

* uplift to pull code from branch that run workflow not the tag

* update healthcheck

* update healthcheck and enable access logs

* update endpoint

* use -p flag to seperate docker compose base and app

* update makefile

* setup tls

* update docker provider

* fix tls config in traefik

* setup network

* update tls config

* update host regex config

* expose port 443

* add gotenberg container

* remove name in docker-compose

* default commit id for deploy

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -3,19 +3,18 @@ name: CD Pipeline
 on:
   workflow_dispatch:
     inputs:
-      commit_id:
-        description: "Commit ID to deploy"
-        required: true
+      image_tag:
+        description: "Image tag to deploy. This can be a commit SHA, or tag. If empty, will use current commit SHA."
+        required: false
         type: string
       environment:
         description: "Environment to deploy to"
         required: true
         type: choice
         options:
-          - dev
           - stg
           - prod
-        default: dev
+        default: stg
 
 env:
   DOCKER_IMAGE: lab-admin-go
@@ -27,11 +26,13 @@ jobs:
     environment: ${{ inputs.environment }}
 
     steps:
-      - name: Checkout specific commit
-        uses: actions/checkout@v5
-        with:
-          ref: ${{ inputs.commit_id }}
-          fetch-depth: 0
+      - name: Show deployment info
+        run: |
+          echo "🚀 Starting deployment..."
+          echo "Repository: ${{ github.repository }}"
+          echo "Source Code SHA: ${{ github.sha }}"
+          echo "Environment: ${{ inputs.environment }}"
+          echo "Image Tag: ${{ inputs.image_tag }}"
 
       - name: Deploy to server via SSH
         uses: appleboy/ssh-action@v1.2.2
@@ -43,13 +44,27 @@ jobs:
           script: |
             set -e
 
-            ls
+            REPO_OWNER=${{ github.event.repository.owner.login }}
+            REPO_NAME=${{ github.event.repository.name }}
+
+            GITHUB_URL="https://github.com/$REPO_OWNER/$REPO_NAME.git"
+            echo $GITHUB_URL
+
+            rm -rf $REPO_NAME
+            git clone $GITHUB_URL
+            cd $REPO_NAME
+            git checkout ${{ github.sha }}
             pwd
 
-            export DOCKER_TAG=${{ inputs.commit_id }}
+            if [ -z "${{ inputs.image_tag }}" ]; then
+              export DOCKER_TAG=${{ github.sha }}
+            else
+              export DOCKER_TAG=${{ inputs.image_tag }}
+            fi
             export ENV=${{ inputs.environment }}
             export DOCKER_USERNAME=${{ vars.DOCKER_USERNAME }}
 
+            make stop-app
             make start-app
 
             echo "Deployment completed successfully!"
@@ -63,22 +78,26 @@ jobs:
               exit 1
             fi
 
-      - name: Health check
-        run: |
-          echo "Waiting for application to be ready..."
-          sleep 30
-
-          # Perform health check if health endpoint is available
-          # Uncomment and modify the URL based on your application
-          # curl -f localhost:9000/health || exit 1
-
-          echo "✅ Deployment completed successfully for commit ${{ inputs.commit_id }} in ${{ inputs.environment }} environment"
+            # Health check
+            for i in {1..10}; do
+            if [ $(curl -s -o /dev/null -w "%{http_code}" localhost:9000/health) -eq 200 ]; then
+              echo "Health check passed!"
+              break
+            else
+              echo "Health check failed, retrying in 5 seconds... ($i/10)"
+              sleep 5
+            fi
+            if [ $i -eq 10 ]; then
+              echo "Health check failed after 10 attempts."
+              exit 1
+            fi
+            done
 
       - name: Notify deployment status
         if: always()
         run: |
           if [ "${{ job.status }}" == "success" ]; then
-            echo "🚀 Deployment SUCCESS: Commit ${{ inputs.commit_id }} deployed to ${{ inputs.environment }}"
+            echo "🚀 Deployment SUCCESS: Tag ${{ inputs.image_tag }} deployed to ${{ inputs.environment }}"
           else
-            echo "💥 Deployment FAILED: Commit ${{ inputs.commit_id }} failed to deploy to ${{ inputs.environment }}"
+            echo "💥 Deployment FAILED: Tag ${{ inputs.image_tag }} failed to deploy to ${{ inputs.environment }}"
           fi
